# Generated by Django 4.0 on 2023-12-08 17:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('healthworker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=100, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('place_of_birth', models.CharField(max_length=100, null=True)),
                ('contact', models.IntegerField(null=True)),
                ('mother_name', models.CharField(max_length=100, null=True)),
                ('father_name', models.CharField(max_length=100, null=True)),
                ('birth_height', models.IntegerField(null=True)),
                ('birth_weight', models.IntegerField(null=True)),
                ('sex', models.CharField(max_length=10, null=True)),
                ('added_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaxapp.barangay')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('dose1', models.BooleanField(null=True)),
                ('dose2', models.BooleanField(null=True)),
                ('dose3', models.BooleanField(null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('recommended_age1', models.CharField(max_length=50, null=True)),
                ('recommended_age2', models.CharField(max_length=50, null=True)),
                ('recommended_age3', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_info', models.TextField(default=None)),
                ('child', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vaxapp.register')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vax_date', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('vaccine_info', models.TextField(default=None)),
                ('brgy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vaxapp.barangay')),
                ('child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vaxapp.register')),
                ('guardian', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
