# Generated by Django 4.0 on 2023-12-08 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0006_remove_guardian_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='added_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vaxapp.guardian'),
        ),
    ]
