# Generated by Django 4.0 on 2023-12-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0008_remove_guardian_email_remove_guardian_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='contact',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
