# Generated by Django 4.0 on 2023-12-09 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaxapp', '0009_guardian_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='guardian',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vaxapp.guardian'),
        ),
    ]
